version: '3.8'

services:
  web:
    build:
      context: ./ERP_PORTILLO
      dockerfile: Dockerfile
    
    command: gunicorn portillo_erp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/ERP_PORTILLO/web/staticfiles
      - media_volume:/home/ERP_PORTILLO/web/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    
     
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  
  frontend: 
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./nginx/ngix-setup.config:/etc/nginx/conf.d/default.conf:ro
      - react_build:/client/dist
    depends_on:
      - web
      - db
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/ERP_PORTILLO/web/staticfiles
      - media_volume:/home/ERP_PORTILLO/web/mediafiles
      - react_build:/var/www/react
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:8080
      - 443:443
    restart: always
    
    depends_on:
      - web
      - frontend
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  static_volume:
  media_volume:
  react_build:
