# Generated by Django 4.2.2 on 2023-08-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
