# Generated by Django 4.2.2 on 2023-07-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='horaio',
            new_name='horario',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.profile'),
        ),
    ]
