# Generated by Django 4.2.2 on 2023-07-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_rename_usuario_usuario_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_detalle',
            name='a_judiciales',
        ),
        migrations.RemoveField(
            model_name='usuario_detalle',
            name='a_penales',
        ),
        migrations.RemoveField(
            model_name='usuario_detalle',
            name='a_policiales',
        ),
    ]
