# Generated by Django 4.2.2 on 2023-07-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_customgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Profile',
        ),
    ]
