# Generated by Django 4.2.2 on 2023-08-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_alter_modulo_permissionss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='dni',
        ),
        migrations.AddField(
            model_name='modulo',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('E', 'Eliminado')], default='A', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
