# Generated by Django 4.2.2 on 2023-07-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_rename_perfil_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
    ]
