# Generated by Django 4.2.2 on 2023-07-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
