# Generated by Django 4.2.2 on 2023-08-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cuenta', '0005_remove_modulo_dni_modulo_estado_modulo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='permissionss',
        ),
        migrations.AddField(
            model_name='modulo',
            name='permissionss_canAdd',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
