# Generated by Django 4.2.2 on 2023-07-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_remove_customuser_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
