# Generated by Django 4.2.2 on 2023-07-11 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_delete_customgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_detalle',
            old_name='usuario',
            new_name='userId',
        ),
    ]
