# Generated by Django 4.2.2 on 2023-08-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_remove_modulo_permissionss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='permissionss_canAdd',
            new_name='permissionss',
        ),
    ]
