# Generated by Django 4.2.2 on 2023-07-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_rename_usuario_usuario_detalle_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_detalle',
            name='dni',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
