# Generated by Django 4.2.2 on 2023-08-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_rename_permissionss_canadd_modulo_permissionss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='permissionss',
        ),
    ]
