# Generated by Django 4.2.2 on 2023-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='codigo',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(null=True, to='cuenta.customgroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(default=None, max_length=8, null=True, unique=True),
        ),
    ]
