# Generated by Django 4.2.2 on 2023-08-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_remove_modulo_permissionss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='model',
            new_name='contentType',
        ),
    ]
