# Generated by Django 4.2.2 on 2023-07-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_alter_usuario_detalle_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_detalle',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
