# Generated by Django 4.2.2 on 2023-08-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_rename_model_modulo_contenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='estado',
        ),
    ]
