# Generated by Django 4.2.2 on 2023-07-12 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_usuario_detalle_documentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_detalle',
            old_name='userId',
            new_name='user_id',
        ),
    ]
