# Generated by Django 4.2.2 on 2023-07-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0011_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
