# Generated by Django 4.2.2 on 2023-08-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0003_alter_campania_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campania',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo'), ('E', 'Eliminado')], default='A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campania',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.proyecto'),
        ),
        migrations.AlterField(
            model_name='campania',
            name='subCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.subcategoria'),
        ),
        migrations.AlterField(
            model_name='campania',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
