export * from "./getProyectos";
export * from "./deleteProyecto";
export * from "./createProyecto";
export * from "./updateProyecto";
export * from "./getProyecto";
export * from "./createImagenProyecto";
export * from "./createVideoProyecto";
export * from "./deleteImagenProyecto";
export * from "./deleteVideoProyecto";